# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Default pre-commit sample file
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# Additional hooks
# Run isort on pre-commit
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        types: [python]
        args: [--profile, black]
# Run black on pre-commit: see https://github.com/psf/black-pre-commit-mirror
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.1.0  # Use a recent stable version
    hooks:
      - id: black
        name: black
        args: ["--line-length", "100"]
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]
